### ISSUE TITLE
RangeError in structure highlighting

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#1060]
```
RangeError: Invalid position 978 in document of length 977
  at lineAt(../node_modules/@codemirror/state/dist/index.js:14:19)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4327:44)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineAt(../node_modules/@codemirror/view/dist/index.js:4422:26)
  at lineBlockAt(../node_modules/@codemirror/view/dist/index.js:5086:39)
  at lineBlockAt(../node_modules/@codemirror/view/dist/index.js:6580:31)
  at positionsForNode(editor/codemirror/structure-highlighting/view.ts:102:28)
  at leave(editor/codemirror/structure-highlighting/view.ts:184:43)
  at iterate(../node_modules/@lezer/common/dist/index.js:355:21)
  at read(editor/codemirror/structure-highlighting/view.ts:155:16)
  at ? (../node_modules/@codemirror/view/dist/index.js:6380:34)
  at Array.map(<anonymous>)
  at measure(../node_modules/@codemirror/view/dist/index.js:6378:42)
  at onScrollChanged(../node_modules/@codemirror/view/dist/index.js:6152:22)
  at wrappedArguments(../node_modules/@codemirror/view/dist/index.js:5548:14)
  at HTMLDivElement.i(../../../../browser/src/helpers.ts:73:23)
```

Now clearer in logging since #1054. This one is unrelated.

**Comment by microbit-matt-hillsdon** [comment]
The code is adding 1 to a position so it seems likely that some straightforward defensiveness would fix. Would be nice to have a repro though.

**Comment by microbit-matt-hillsdon** [comment]
So we're finding the lineBlock for the start of the body. I think that starts with the colon.
But visually we want to highlight the next line, so we're moving to the next line via the +1.
But that position might not exist.
So far as I can tell it routinely does not exist in scenarios like

```python
if True: pass
```

...but lineBlockAt doesn't fail in in these obvious reproductions.

**Comment by microbit-matt-hillsdon** [comment]
I'm going to extend the minimal fix above to also address this related inconsistency:

![image](https://user-images.githubusercontent.com/44397098/199689003-2c5e0354-f473-4fba-8c0b-1af71638e912.png)

Left is my updated fix, right is current behaviour.
